{
 "title": "Network Data",
 "description": "Network data from nlbwmon on OpenWrt ",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Sent + Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, sum by(hostname, ip) (\n  rate(nlbwmon_rx_bytes{hostname=~\".+\"}[$__rate_interval])\n  +\n  rate(nlbwmon_tx_bytes{hostname=~\".+\"}[$__rate_interval])\n) * 8)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, sum by(hostname, ip) (\n  rate(nlbwmon_rx_bytes{hostname=~\".+\"}[$__rate_interval])\n) * 8)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Sent + Received",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum by(hostname, ip) (\n  increase(nlbwmon_rx_bytes{hostname=~\".+\"}[$__range])\n  +\n  increase(nlbwmon_tx_bytes{hostname=~\".+\"}[$__range])\n))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum by(hostname, ip) (\n  increase(nlbwmon_tx_bytes{hostname=~\".+\"}[$__range])\n))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Sent + Received",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum by(hostname, ip) (\n  increase(nlbwmon_rx_bytes{hostname=~\".+\"}[$__range])\n  +\n  increase(nlbwmon_tx_bytes{hostname=~\".+\"}[$__range])\n))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum by(hostname, ip) (\n  increase(nlbwmon_tx_bytes{hostname=~\".+\"}[$__range])\n))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Sent + Received",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum by(hostname, ip) (\n\n  nlbwmon_rx_bytes{hostname=~\".+\"}\n\n  +\n\n  nlbwmon_tx_bytes{hostname=~\".+\"}\n\n))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum by(layer7) (\n  increase(nlbwmon_rx_bytes{hostname=~\".+\"}[$__range])\n  +\n  increase(nlbwmon_tx_bytes{hostname=~\".+\"}[$__range])\n))",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}